### ISSUE TITLE
Suggestions for characters

### ISSUE THREAD

**Issue by usrshare** [ctrlcctrlv/lcd-font#5]
First, I have to say, this is a really well-done font. I haven't seen a 14-segment font with support for so many character sets before, and this looks like a stellar job.

I do have certain suggestions for some Cyrillic characters. I would have forked it and made a pull-request, but I don't know how to properly hint characters in FontForge.

The letters "Жж" look terrible. The shape itself is wrong, as the horizontal line in the middle shouldn't extend beyond any of the diagonal lines.  Judging from my Russian experience, the best shape for that letter would look like this:

![2016-07-14-101458_59x76_scrot](https://cloud.githubusercontent.com/assets/84842/16831142/f4b7b2a0-49ab-11e6-9980-0233e21f8255.png)

The Cyrillic letters "Дд" and "Лл" can borrow glyphs from the greek uppercase delta and lambda. Sure, they don't look exactly alike, but, from what I know, a Russian-speaking person will recognize them easier than the ones currently used.

**Comment by ctrlcctrlv** [comment]
Thank you very much for your suggestions :) Advice from someone who actually speaks the language helps!

I'm just finishing up #4 and then I'll come back to this.

**Comment by ctrlcctrlv** [comment]
Fixed in version 2.
